# Agent Skills - Nix Module
# =========================
# Provides declarative management of agent skills using Nix.
#
# This module can be imported into your home.nix configuration
# to manage agent skills declaratively.
#
# Usage in home.nix:
#   imports = [
#     ./agent-skills.nix
#   ];
#
#   programs.agent-skills = {
#     enable = true;
#     targets = {
#       claude = {
#         enable = true;
#         path = ".claude/skills";
#       };
#       opencode = {
#         enable = true;
#         path = ".config/opencode/skills";
#       };
#     };
#     skills = [
#       "anthropic:pdf"
#       "anthropic:docx"
#       "anthropic:mcp-builder"
#     ];
#   };

{ config, lib, pkgs, ... }:

let
  cfg = config.programs.agent-skills;

  # Skill sources configuration
  defaultSources = {
    anthropic = {
      type = "git";
      url = "https://github.com/anthropics/skills.git";
      branch = "main";
      path = "skills";
    };
  };

  # Generate skills.yaml from Nix config
  skillsYaml = pkgs.writeText "skills.yaml" ''
    # Auto-generated by Nix - do not edit manually
    # Edit your home.nix configuration instead

    targets:
    ${lib.concatStringsSep "\n" (lib.mapAttrsToList (name: target: ''
      ${name}:
        enabled: ${lib.boolToString target.enable}
        path: ~/${target.path}
    '') cfg.targets)}

    sources:
    ${lib.concatStringsSep "\n" (lib.mapAttrsToList (name: source: ''
      ${name}:
        type: ${source.type}
        url: ${source.url}
        branch: ${source.branch}
        path: ${source.path}
    '') (cfg.sources // defaultSources))}

    enabled:
    ${lib.concatStringsSep "\n" (map (skill: "  - ${skill}") cfg.skills)}
  '';

  # Agent skills CLI script wrapper
  agentSkillsScript = pkgs.writeShellScriptBin "agent-skills" ''
    export AGENT_SKILLS_CONFIG="${config.xdg.configHome}/agent-skills/skills.yaml"
    export AGENT_SKILLS_DIR="${config.home.homeDirectory}/.agent-skills"
    export PATH="${lib.makeBinPath [ pkgs.yq-go pkgs.git ]}:$PATH"

    ${builtins.readFile ../dot_local/bin/executable_agent-skills}
  '';

in {
  options.programs.agent-skills = {
    enable = lib.mkEnableOption "Agent Skills Package Manager";

    package = lib.mkOption {
      type = lib.types.package;
      default = agentSkillsScript;
      description = "The agent-skills package to use.";
    };

    targets = lib.mkOption {
      type = lib.types.attrsOf (lib.types.submodule {
        options = {
          enable = lib.mkOption {
            type = lib.types.bool;
            default = false;
            description = "Whether to enable this target.";
          };
          path = lib.mkOption {
            type = lib.types.str;
            description = "Path relative to home directory for skills.";
          };
        };
      });
      default = {
        claude = {
          enable = true;
          path = ".claude/skills";
        };
        codex = {
          enable = false;
          path = ".codex/skills";
        };
        opencode = {
          enable = false;
          path = ".config/opencode/skills";
        };
      };
      description = "Target agents and their skill directories.";
    };

    sources = lib.mkOption {
      type = lib.types.attrsOf (lib.types.submodule {
        options = {
          type = lib.mkOption {
            type = lib.types.enum [ "git" "local" ];
            default = "git";
            description = "Source type (git or local).";
          };
          url = lib.mkOption {
            type = lib.types.str;
            default = "";
            description = "Git repository URL.";
          };
          branch = lib.mkOption {
            type = lib.types.str;
            default = "main";
            description = "Git branch to use.";
          };
          path = lib.mkOption {
            type = lib.types.str;
            default = ".";
            description = "Path within the source containing skills.";
          };
        };
      });
      default = {};
      description = "Additional skill sources.";
    };

    skills = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [];
      example = [ "anthropic:pdf" "anthropic:docx" ];
      description = "List of skills to enable (format: source:skill-name).";
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages = [
      cfg.package
      pkgs.yq-go
    ];

    # Link the generated skills.yaml
    xdg.configFile."agent-skills/skills.yaml".source = skillsYaml;

    # Create target directories
    home.activation.createAgentSkillsTargets = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      ${lib.concatStringsSep "\n" (lib.mapAttrsToList (name: target:
        lib.optionalString target.enable ''
          $DRY_RUN_CMD mkdir -p $HOME/${target.path}
        ''
      ) cfg.targets)}
    '';

    # Run sync after activation (optional - can be run manually)
    home.activation.syncAgentSkills = lib.hm.dag.entryAfter [ "createAgentSkillsTargets" ] ''
      if [[ -z "''${DRY_RUN:-}" ]]; then
        $VERBOSE_ECHO "Syncing agent skills..."
        ${cfg.package}/bin/agent-skills update 2>/dev/null || true
        ${cfg.package}/bin/agent-skills sync 2>/dev/null || true
      fi
    '';
  };
}
