#!/bin/sh

# Linuxへのsshログインをslackへ通知する
IP=`who | cut -d '(' -f 2 | sed -e 's/)//g'`
USER=`who | awk -F' ' '{print $1}' `
HOSTNAME=`hostname`

curl -X POST --data-urlencode 'payload={"channel": "#login_log", "username": "toro", "text": " '"$USER"'で'"$HOSTNAME"'に接続しました！ from  '"$IP"'", "icon_emoji": ":sushi:"}'  https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXX
