#!/bin/sh

# Linuxへのsshログインをslackへ通知する

IP=`who am i | cut -d '(' -f 2 | sed -e 's/)//g'`
curl -X POST --data-urlencode 'payload={"channel": "#alert", "username": "toro", "text": "だれかがこのIPから接続しました！ '"${IP}"'", "icon_emoji": ":sushi:"}' 
https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXX
